In [4]:
import pandas as pd
import numpy as np

In [2]:
pred_file = "../output/class_pred_16.v2.csv"
baseline_file = "../output/baseline.csv"
test_file = "../input/en_test_2.csv"

In [5]:
pred_df = pd.read_csv(pred_file)
baselin_df = pd.read_csv(baseline_file)
test_df = pd.read_csv(test_file)

In [8]:
labels = ['PLAIN', 'PUNCT', 'DATE', 'LETTERS', 'CARDINAL', 'VERBATIM',
          'DECIMAL', 'MEASURE', 'MONEY', 'ORDINAL', 'TIME', 'ELECTRONIC',
          'DIGIT', 'FRACTION', 'TELEPHONE', 'ADDRESS']
label2index = dict(zip(labels, range(len(labels))))
index2label = dict([(v, k) for k, v in label2index.items()])

In [7]:
pred_df["class_pred"].value_counts()

0.0     689131
1.0     193491
2.0      26784
3.0      16302
4.0      13481
5.0       9920
7.0       2287
9.0       1113
11.0       948
6.0        897
8.0        557
12.0       462
14.0       353
10.0       152
13.0       106
15.0        62
Name: class_pred, dtype: int64

In [18]:
pred_df.loc[pred_df["class_pred"].apply(lambda i: index2label[i]) == "DECIMAL"]

              id        before  class_pred
1165       101_9          0.59         6.0
1573       137_7      28 years         6.0
2408      204_10         195.7         6.0
2722       228_5           .54         6.0
3195      265_13            .1         6.0
4135      342_10         197.1         6.0
4178       347_6           .10         6.0
5740       472_7       .403053         6.0
6187       509_9            .4         6.0
8743       702_8           1.0         6.0
8748      702_13           2.6         6.0
9170      737_15    45 minutes         6.0
10188      816_0          7.99         6.0
13202    1044_10       1,238.5         6.0
20520     1593_3      22 years         6.0
21005    1630_10         990.8         6.0
21990    1702_12      15 years         6.0
23081    1790_10          13.2         6.0
25571    1989_10         248.5         6.0
25818     2010_9            .4         6.0
26814     2085_3          .192         6.0
26818     2085_7          .195         6.0
26879     2089_3         216.8         6.0
27401     2132_5         11.81         6.0
33474     2595_7          5.56         6.0
34128     2644_9           .32         6.0
34821     2701_4       10.1542         6.0
39577    3057_10         409.8         6.0
39992    3085_12         107.1         6.0
44504    3437_21    55 billion         6.0
...          ...           ...         ...
938223  68694_25            .8         6.0
938224  68694_26            .3         6.0
938919   68750_5           2.4         6.0
938924  68750_10          63.5         6.0
940853  68891_10    10 million         6.0
941580   68941_2         2.266         6.0
942691   69020_6         224.9         6.0
942694   69020_9         213.8         6.0
942974   69040_7           2.2         6.0
943740   69093_5      10 years         6.0
944060  69114_15          .180         6.0
944481   69149_7      15 years         6.0
945773   69245_8          .451         6.0
945782  69245_17          .452         6.0
947069   69337_2       10.1111         6.0
947072   69337_5         .1365         6.0
947074   69337_7     2648.2010         6.0
947075   69337_8        .05381         6.0
947767  69386_10   320 million         6.0
947769  69386_12   190 million         6.0
947869   69394_5   3.5 million         6.0
948197   69418_3      42 years         6.0
951099   69634_0  20.7 million         6.0
951106   69634_7   8.6 million         6.0
951113  69634_14   0.7 million         6.0
951245  69643_19           9.2         6.0
954231   69864_4         24.06         6.0
954232   69864_5           .07         6.0
955335   69948_3  3.25 million         6.0
955693   69976_5           6.4         6.0

[897 rows x 3 columns]

In [22]:
pred_df.loc[pred_df["class_pred"].apply(lambda i: index2label[i]) == "ELECTRONIC"]

,id,before,class_pred
2632,220_11,and/or,11.0
4038,335_3,#ZumaMustFall,11.0
4282,353_17,off-season,11.0
5220,428_4,.USA,11.0
6678,546_1,Stone.com,11.0
8034,645_2,2016.in,11.0
9835,786_24,http://wwwusers.di.uniroma1.it/~velardi/IEEE_C...,11.0
10308,828_0,OnlineBeccaloni,11.0
11774,938_2,http://www.amnh.org/exhibitions/permanent-exhi...,11.0
12519,1001_3,http://www.governor.nsw.gov.au/governor/vice-r...,11.0
12820,1021_15,NJ.com,11.0
13186,1043_11,semi-finalist,11.0
13380,1057_2,/ˈsɪl.ver.sti,11.0
13926,1102_8,hundredshttp://www.cricinfo.com/westindies/con...,11.0
14629,1156_2,::,11.0
15864,1244_20,http://www.cpukforum.com/forum/index.php,11.0
16754,1315_14,full-time,11.0
22089,1712_1,#RHOMelbourne,11.0
22394,1735_11,semi-final,11.0
22455,1739_2,http://www.nytimes.com/2005/09/11/magazine/amo...,11.0
22688,1761_5,Machine.KingsofMaroussi.com,11.0
23937,1860_10,and/or,11.0
25142,1954_4,#Charlotte,11.0
25819,2010_10,http://www.iranicaonline.org/articles/fath-ali...,11.0
32452,2516_14,http://www.afhra.af.mil/,11.0
32455,2517_1,gillinghamfootballclub.com,11.0
33741,2616_3,::,11.0
34135,2644_16,//www.marinecorpstimes.com/news/2012/07/ap-mar...,11.0
36076,2792_2,http://www.popmatters.com/review/paul-bowles/E...,11.0
36197,2801_8,anti-war,11.0
...,...,...,...
916457,67138_2,www.biolib.cz,11.0
916612,67147_19,and/or,11.0
917273,67196_14,BOWL.com,11.0
918042,67251_17,https://www.cia.gov/library/publications/the-w...,11.0
919052,67321_9,http://www.civilwararchive.com/Unreghst/unmiar...,11.0
919127,67326_11,reporthttps://web.archive.org/web/201110150207...,11.0
919273,67340_0,BioLib.cz,11.0
923822,67674_9,MLSnews.net,11.0
924891,67748_0,BioLib.cz,11.0
926527,67866_0,BioLib.cz,11.0
931551,68228_2,Ultratop.be,11.0
932679,68307_12,WatchESPN.com,11.0
935598,68511_0,BioLib.cz,11.0
938976,68754_5,high-rise,11.0
939210,68769_8,bangladeshbd.org,11.0
939471,68790_11,.pdf,11.0
940430,68861_7,http://winnipeg.ca/clkdmis/documents/c/2006/a6...,11.0
943352,69066_0,BioLib.cz,11.0
943563,69081_0,Barbados.gov.bb,11.0
943922,69104_7,Snopes.com,11.0
947950,69400_19,semi-final,11.0
951175,69639_2,Fussballdaten.de,11.0
952168,69714_5,Historywc.rootsweb.com,11.0
952475,69737_3,::,11.0
952630,69746_6,high-speed,11.0
953307,69795_0,high-speed,11.0
953980,69843_9,semi-final,11.0
954139,69854_19,http://dos.myflorida.com/elections/data-statis...,11.0
954640,69895_0,Changsha.com,11.0
954765,69904_3,anti-war,11.0

In [6]:
test_df[:50]

    sentence_id  token_id          before
0             0         0         Another
1             0         1       religious
2             0         2          family
3             0         3              is
4             0         4              of
5             0         5          Hazrat
6             0         6          Sayyed
7             0         7           Ahmad
8             0         8             and
9             0         9             his
10            0        10          nephew
11            0        11          Hazrat
12            0        12           Abdul
13            0        13             Haq
14            0        14               .
15            1         0             The
16            1         1            free
17            1         2          webapp
18            1         3   functionality
19            1         4        contains
20            1         5  advertisements
21            1         6          geared
22            1         7              to
23            1         8           small
24            1         9      businesses
25            1        10               .
26            2         0         Kuklick
27            2         1               ,
28            2         2               p
29            2         3               .
30            2         4              75
31            2         5         Kuklick
32            2         6               ,
33            2         7               p
34            2         8               .
35            2         9              76
36            2        10        Westcott
37            2        11               ,
38            2        12               p
39            2        13               .
40            2        14             124
41            2        15         Kuklick
42            2        16               ,
43            2        17              pp
44            2        18               .
45            3         0               "
46            3         1            2010
47            3         2            FINA
48            3         3           World
49            3         4        Swimming

In [7]:
ids_a = np.array(list(map(lambda tup: str(tup[0]) + "_" + str(tup[1]),
                         zip(test_df["sentence_id"].values,
                             test_df["token_id"].values))))

In [8]:
test_df["id"] = ids_a

In [9]:
compare_df = pd.merge(test_df, baselin_df, on=["id"])
compare_df = pd.merge(compare_df, pred_df, on=["id"])
compare_df = compare_df[["id", "before", "after","class_pred"]]

In [10]:
compare_df["equal"] = (compare_df["before"] == compare_df["after"])

In [11]:
compare_df[:100]

      id          before                          after  class_pred  equal
0    0_0         Another                        Another         0.0   True
1    0_1       religious                      religious         0.0   True
2    0_2          family                         family         0.0   True
3    0_3              is                             is         0.0   True
4    0_4              of                             of         0.0   True
5    0_5          Hazrat                         Hazrat         0.0   True
6    0_6          Sayyed                         Sayyed         0.0   True
7    0_7           Ahmad                          Ahmad         0.0   True
8    0_8             and                            and         0.0   True
9    0_9             his                            his         0.0   True
10  0_10          nephew                         nephew         0.0   True
11  0_11          Hazrat                         Hazrat         0.0   True
12  0_12           Abdul                          Abdul         0.0   True
13  0_13             Haq                            Haq         0.0   True
14  0_14               .                              .         0.0   True
15   1_0             The                            The         0.0   True
16   1_1            free                           free         0.0   True
17   1_2          webapp                         webapp         0.0   True
18   1_3   functionality                  functionality         0.0   True
19   1_4        contains                       contains         0.0   True
20   1_5  advertisements                 advertisements         0.0   True
21   1_6          geared                         geared         0.0   True
22   1_7              to                             to         0.0   True
23   1_8           small                          small         0.0   True
24   1_9      businesses                     businesses         0.0   True
25  1_10               .                              .         0.0   True
26   2_0         Kuklick                        Kuklick         0.0   True
27   2_1               ,                              ,         0.0   True
28   2_2               p                              p         0.0   True
29   2_3               .                              .         0.0   True
..   ...             ...                            ...         ...    ...
70   4_6              Dn                            d n         0.0  False
71   4_7        includes                       includes         0.0   True
72   4_8     reflections                    reflections         0.0   True
73   4_9              in                             in         0.0   True
74  4_10           lines                          lines         0.0   True
75  4_11               .                              .         0.0   True
76   5_0             The                            The         0.0   True
77   5_1        museum's                       museum's         0.0   True
78   5_2      exhibition                     exhibition         0.0   True
79   5_3            hall                           hall         0.0   True
80   5_4        occupies                       occupies         0.0   True
81   5_5           3,400    three thousand four hundred         1.0  False
82   5_6          square                         square         0.0   True
83   5_7          meters                         meters         0.0   True
84   5_8               (                              (         0.0   True
85   5_9       10,200 ft  ten thousand two hundred feet         1.0  False
86  5_10               ²                        squared         1.0  False
87  5_11               )                              )         0.0   True
88  5_12             and                            and         0.0   True
89  5_13             its                            its         0.0   True
90  5_14         library                        library         0.0   True
91  5_15        contains                       contains         0.0   True
92  5_16           7,000                 seven thousand         1.0  False
93  5_17           books                          books         0.0   True
94  5_18               .                              .         0.0   True
95   6_0               "                              "         0.0   True
96   6_1        Japanese                       Japanese         0.0   True
97   6_2          German                         German         0.0   True
98   6_3       relations                      relations         0.0   True
99   6_4               ,                              ,         0.0   True

[100 rows x 5 columns]

In [12]:
diff_df = compare_df.iloc[compare_df["class_pred"].values != list(map(float, (~compare_df["equal"].values)))]
diff_df

,id,before,after,class_pred,equal
54,3_9,-,-,1.0,True
57,3_12,metre,meter,0.0,False
66,4_2,D,D,1.0,True
70,4_6,Dn,d n,0.0,False
383,27_8,p,p,1.0,True
434,31_9,11.8 MB,11.8 MB,1.0,True
571,40_7,metres,meters,0.0,False
575,40_11,-,-,1.0,True
704,49_1,http://www.britannica.com/EBchecked/topic/2852...,http://www.britannica.com/EBchecked/topic/2852...,1.0,True
742,52_9,http://search.eb.com/eb/article-9061377,http://search.eb.com/eb/article-9061377,1.0,True
748,52_15,::,::,1.0,True
779,54_13,Café,cafe,0.0,False
789,55_6,kilometres,kilometers,0.0,False
798,55_15,kilometres,kilometers,0.0,False
918,63_16,-,-,1.0,True
929,64_2,BOGOF,b o g o f,0.0,False
934,64_7,p,p,1.0,True
940,64_13,p,p,1.0,True
942,64_15,BOGOF,b o g o f,0.0,False
1036,71_0,dr,doctor,0.0,False
1173,79_1,jr,junior,0.0,False
1216,81_6,Programme,program,0.0,False
1368,92_0,vol,volume,0.0,False
1603,106_10,-,-,1.0,True
1640,108_4,kilometres,kilometers,0.0,False
1933,126_10,emphasise,emphasize,0.0,False
2021,130_20,Г,Г,1.0,True
2022,130_21,у,у,1.0,True
2023,130_22,г,г,1.0,True
2024,130_23,о,о,1.0,True
...,...,...,...,...,...
1085840,69823_3,vol,volume,0.0,False
1085920,69829_17,recognised,recognized,0.0,False
1085964,69832_2,Jazzhouse.orgChris,Jazzhouse.orgChris,1.0,True
1086230,69848_0,Q,Q,1.0,True
1086316,69854_4,978-0-271-02526-1,978-0-271-02526-1,1.0,True
1086477,69865_12,52.4 mm,52.4 mm,1.0,True
1086762,69882_12,Nur,n u r,0.0,False
1086775,69883_8,metres,meters,0.0,False
1086785,69883_18,12.348 km²,12.348 km²,1.0,True
1086787,69883_20,7.67mi²,7.67mi²,1.0,True
1086822,69886_2,-,-,1.0,True
1087155,69907_3,-,-,1.0,True
1087231,69912_7,e,e,1.0,True
1087249,69913_15,-,-,1.0,True
1087384,69921_16,-,-,1.0,True
1087407,69923_1,Uniao,u n i a o,0.0,False
1087466,69928_5,Ared,a r e d,0.0,False
1087471,69928_10,ሰ,ሰ,1.0,True
1087472,69928_11,ይ,ይ,1.0,True
1087473,69928_12,ፈ,ፈ,1.0,True
1087474,69928_13,አ,አ,1.0,True
1087475,69928_14,ር,ር,1.0,True
1087476,69928_15,ድ,ድ,1.0,True
1087478,69928_17,ኛ,ኛ,1.0,True
1087533,69932_0,SignOnSanDiego.co,SignOnSanDiego.co,1.0,True
1087543,69933_3,metres,meters,0.0,False
1087914,69956_6,SCOOP,SCOOP,1.0,True
1087917,69956_9,-,-,1.0,True
1087950,69959_4,jr,junior,0.0,False
1088259,69979_3,-,-,1.0,True

In [13]:
diff_df.shape[0] / compare_df.shape[0]

0.013198121561984412